x-backend-common: &backend-common
  image: backend:v1
  build:
    args:
      - NODE_ENV=development
    context: backend
    target: development
  container_name: backendapp
  command: npm run start-watch
  restart: always
  environment:
    - DATABASE_DB=example
    - DATABASE_USER=root
    - DATABASE_PASSWORD=/run/secrets/db-password
    - DATABASE_HOST=maxscale
    - NODE_ENV=development
    - REDIS_HOST=redis
    - REDIS_PORT=6379
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
    - "traefik.http.routers.backend.entrypoints=web"
    - "traefik.http.services.backend.loadbalancer.server.port=80"
    - "traefik.http.routers.backend.middlewares=backend-strip,backend-auth,backend-ratelimit"
    - "traefik.http.middlewares.backend-strip.stripprefix.prefixes=/api"
    - "traefik.docker.network=back-tier"
    #HTTPS router
    # ForwardAuth middleware
    - "traefik.http.middlewares.backend-auth.forwardauth.address=http://auth-service:3000/auth"
    - "traefik.http.middlewares.backend-auth.forwardauth.trustForwardHeader=true"
    - "traefik.http.routers.backend-secure.rule=PathPrefix(`/api`)"
    - "traefik.http.routers.backend-secure.entrypoints=websecure"
    - "traefik.http.routers.backend-secure.tls=true"
    - "traefik.http.middlewares.backend-ratelimit.ratelimit.average=1000"
    - "traefik.http.middlewares.backend-ratelimit.ratelimit.burst=2000"
    - "traefik.http.routers.backend-secure.middlewares=backend-strip,backend-auth,backend-ratelimit"
    
    
  expose:
    - "80"                    # reachable inside the network only
  secrets:
    - db-password
  volumes:
    - ./backend/src:/code/src:ro
    - ./backend/package.json:/code/package.json
    - ./backend/package-lock.json:/code/package-lock.json
    - back-notused:/opt/app/node_modules
  networks:
    - back-tier                # treafik <-> backend
    - data-tier                # backend <-> db
    - monitoring
  depends_on:
    db-primary:
      condition: service_healthy
  cpus: "0.5"
  mem_limit: 128m
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "3"

services:
  redis:
    image: redis:8-alpine
    container_name: redis
    restart: unless-stopped

    command: redis-server --appendonly yes

    volumes:
      - redis-data:/data

    networks:
      - data-tier

    expose:
      - "6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yml:ro
      # Required for Promtail to read container logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    ports:
    -  "9080:9080"
    networks:
      - monitoring
    depends_on:
      - loki
  cadvisor:
    image: ghcr.io/google/cadvisor:v0.60.5
    container_name: cadvisor
    restart: unless-stopped

    ports:
    - "8081:8080"

    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker:/var/lib/docker:ro

    networks:
    - monitoring

  prometheus:
    image: prom/prometheus:v3.13.1
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro

    networks:
      - monitoring

    depends_on:
      - cadvisor

  grafana:
    image: grafana/grafana:13.1.1
    container_name: grafana
    restart: unless-stopped

    ports:
      - "3001:3000"

    networks:
      - monitoring

    depends_on:
      - prometheus

    volumes:
      - grafana-data:/var/lib/grafana
  traefik:
    image: traefik:v3.7.8
    container_name: traefik
    restart: unless-stopped

    command:
      - --configFile=/etc/traefik/traefik.yml

    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"

    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/certs:/certs:ro

    networks:
      - front-tier
      - back-tier
  k6:
    build:
      context: ./k6
    container_name: k6
    networks:
      - front-tier
    volumes:
      - ./k6/scripts:/scripts:ro
    working_dir: /scripts
    entrypoint: ["sleep", "infinity"]

  backend1:
    <<: *backend-common
    container_name: backend1

  backend2:
    <<: *backend-common
    container_name: backend2
  maxscale:
    image: mariadb/maxscale:24.02
    container_name: maxscale
    restart: unless-stopped

    ports:
      - "8989:8989"

    volumes:
      - ./maxscale/maxscale.cnf:/etc/maxscale.cnf:ro

    networks:
      - back-tier
      - data-tier

    depends_on:
      db-primary:
        condition: service_healthy
      db-replica:
        condition: service_healthy
      #db-init:
       # condition: service_completed_successfully
  db-primary:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    #image: mariadb:10.6
    build:
      context: ./mariadb
      dockerfile: Dockerfile.primary
    image: mariadb-primary:10.6
    container_name: dbprim
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
      #- ./mariadb/primary.cnf:/etc/mysql/conf.d/primary.cnf:ro
    networks:
      - data-tier 
      - back-tier 
      # isolated: unreachable from treafik & frontend 
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    cpus: "0.5"
    mem_limit: 128m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  db-replica:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    #image: mariadb:10.6
    build:
      context: ./mariadb
      dockerfile: Dockerfile.replica
    image: mariadb-replica:10.6
    container_name: dbrep
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-replica-data:/var/lib/mysql
      #- ./mariadb/replica.cnf:/etc/mysql/conf.d/replica.cnf:ro
    networks:
      - data-tier  
      - back-tier 
      # isolated: unreachable from treafik & frontend
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    cpus: "0.5"
    mem_limit: 128m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  db-backup:
    build:
      context: ./backup
    container_name: db-backup
    restart: unless-stopped

    depends_on:
      - db-primary

    secrets:
      - db-password

    environment:
      - MYSQL_HOST=db-primary
      - MYSQL_DATABASE=example
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password

    volumes:
      - ./backup:/backup
      - db-data:/var/lib/mysql:ro

    networks:
      - data-tier

    command: >
      bash -c "
       chmod +x /backup/backup.sh &&
       crontab /backup/crontab &&
       exec cron -f
       "

  mysqld-exporter:
    image: prom/mysqld-exporter:v0.14.0
    container_name: mysqld-exporter
    restart: unless-stopped

    environment:
      DATA_SOURCE_NAME: "exporter:exporter_password@(db-primary:3306)/"

    expose:
      - "9104"

    depends_on:
      db-primary:
        condition: service_healthy

    networks:
      - data-tier
      - monitoring

  frontend:
    image: frontend:v1
    build:
      context: frontend
      target: development
    container_name: frontapp
    expose:
      - "3000"                   # reachable inside the network only

    labels:
     - "traefik.enable=true"

      # HTTP Router
     - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
     - "traefik.http.routers.frontend.entrypoints=web"
     
      # HTTPS Router
     - "traefik.http.routers.frontend-secure.rule=PathPrefix(`/`)"
     - "traefik.http.routers.frontend-secure.entrypoints=websecure"
     - "traefik.http.routers.frontend-secure.tls=true"
     - "traefik.http.routers.frontend-secure.tls.certresolver=letsencrypt"

      # Service
     - "traefik.http.services.frontend.loadbalancer.server.port=3000"    
    volumes:
      - ./frontend/src:/code/src
      - /code/node_modules
    networks:
      - front-tier # treafik <-> frontend only
    restart: unless-stopped
    healthcheck:
      test: ["CMD","node","-e","require('http').get('http://localhost:3000',res=>process.exit(res.statusCode===200?0:1)).on('error',()=>process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    cpus: "0.5"
    mem_limit: 500m

  auth-service:
    build:
      context: auth-service
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "3002:3000"
    networks:
      - front-tier 
      - back-tier
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    networks:
      - monitoring
      
  #db-init:
   # image: mariadb:10.6
    #container_name: db-init
    #depends_on:
     # db-primary:
        #condition: service_healthy
      #db-replica:
        #condition: service_healthy
    #secrets:
      #- db-password
    #volumes:
     # - ./mariadb/init-users.sql:/init-users.sql:ro
      #- ./mariadb/ensure-users.sh:/ensure-users.sh:ro
    #entrypoint: ["bash", "/ensure-users.sh"]
    #networks:
     # - data-tier
    #restart: "no"
networks:
  front-tier:
    name: front-tier
  back-tier:
    name: back-tier
  data-tier:
    name: data-tier
  monitoring:
    name: monitoring
volumes:
  back-notused:
  db-data:
  grafana-data:
  loki-data:
  redis-data:
  db-replica-data:

secrets:
  db-password:
    file: db/password.txt
